name: KrishiMitram
description: "Aims to smart farming and make farmers to grow with tech ."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"  # You can specify the range if needed

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.9.0
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.6.1
  firebase_storage: ^12.3.7
  image_picker: ^1.1.2
  http: ^1.2.2
  path_provider: ^2.1.5
  shared_preferences: ^2.2.2
  firebase_app_check:
  font_awesome_flutter: ^10.1.0
  google_sign_in: ^6.2.2
  weather: ^3.1.1
  intl: ^0.20.2
  xml: ^6.5.0
  flutter_screenutil: ^5.9.3
  provider: ^6.1.2
  google_fonts: ^6.2.1
  internet_connection_checker_plus: ^2.7.0
  remixicon: ^1.3.0
  connectivity_plus: ^6.1.2
  loading_animation_widget: ^1.2.0+4
  flutter_inappwebview:
  webview_flutter:
  
#  flutter_svg :
#  permission_handler: ^11.3.1
#  flutter_sms: 2.3.3
#  sms_advanced:
#  sms_advanced:

android:
  app:
    label: "smart Farm"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: "^0.14.3"
  flutter_native_splash: ^2.4.4




#flutter pub pub run flutter_native_splash:create
flutter_native_splash:
  android: true
  ios: false
  web: false
  color: "#DFFFD6"  # Black color using hex code
  image: "assets/Logos/splash.jpg"  # Path to your splash image




#flutter pub run flutter_launcher_icons:main
flutter_launcher_icons:
    android: false
    ios: true
    image_path: "assets/Logos/splash.jpg"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - lib/data/cityCodes.xml
    - assets/Team/
    - assets/Logos/

    # Make sure your images are inside assets/images/ folder

